app_name: "basic"
releases:
  - name: "release"
    resources:
      cpu: "50m"
      memory: "256Mi"
    action:
      command:
        - echo
        - hello
services:
  - name: "tacokumo-bot"
    command:
      - "/tacokumo-bot" 
    healthcheck:
      process:
        command:
          - echo
          - hello
    scale:
      min: 1
      max: 100
      metric:
        type: "error_rate"
        threshold: 99
    machine:
      cpu: "50m"
      memory: "256Mi"
      flavor: "m1.xlarge"
build:
  image: "ghcr.io/tacokumo/tacokumo-bot:main-647d918"
